version: 2
updates:
  - package-ecosystem: "docker"
    target-branch: "dev"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "daily"
